### ISSUE TITLE
Error to build with latest Ghidra 10.2.2

### ISSUE THREAD

**Issue by bvernoux** [Nalen98/GhidraEmu#3]
GhidraEmu actual code cannot be built with Ghidra 10.2.2 with following warning/errors:
```
> Task :compileJava
GhidraEmu\src\main\java\byteviewerEmu\ByteViewerPanel.java:26: error: cannot find symbol
import docking.help.Help;
                   ^
  symbol:   class Help
  location: package docking.help
GhidraEmu\src\main\java\byteviewerEmu\ByteViewerPanel.java:27: error: cannot find symbol
import docking.help.HelpService;
                   ^
  symbol:   class HelpService
  location: package docking.help
GhidraEmu\src\main\java\byteviewerEmu\ByteViewerComponent.java:26: error: cannot find symbol
import docking.help.Help;
                   ^
  symbol:   class Help
  location: package docking.help
D:\_proj\Ghidra\GhidraEmu\src\main\java\byteviewerEmu\ByteViewerComponent.java:27: error: cannot find symbol
import docking.help.HelpService;
                   ^
  symbol:   class HelpService
  location: package docking.help
GhidraEmu\src\main\java\byteviewerEmu\ByteViewerPanel.java:827: error: cannot find symbol
                HelpService help = Help.getHelpService();
                ^
  symbol:   class HelpService
  location: class ByteViewerPanel
GhidraEmu\src\main\java\byteviewerEmu\ByteViewerPanel.java:827: error: cannot find symbol
                HelpService help = Help.getHelpService();
                                   ^
  symbol:   variable Help
  location: class ByteViewerPanel
GhidraEmu\src\main\java\byteviewerEmu\ByteViewerComponent.java:750: error: cannot find symbol
                HelpService helpService = Help.getHelpService();
                ^
  symbol:   class HelpService
  location: class ByteViewerComponent
GhidraEmu\src\main\java\byteviewerEmu\ByteViewerComponent.java:750: error: cannot find symbol
                HelpService helpService = Help.getHelpService();
                                          ^
  symbol:   variable Help
  location: class ByteViewerComponent
GhidraEmu\src\main\java\ghidraemu\GhidraEmuPlugin.java:57: warning: [removal] ProgramPlugin(PluginTool,boolean,boolean) in ProgramPlugin has been deprecated and marked for removal
                super(tool, true, true);
                ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
8 errors
1 warning

> Task :compileJava FAILED

FAILURE: Build failed with an exception.
```
